version: '3.5'

services:

  localstack:
    image: localstack/localstack:0.12.7
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=sns,sqs
    volumes:
      - ./localstack:/docker-entrypoint-initaws.d
