cloud:
  aws:
    credentials:
      access-key: ''
      secret-key: ''
    region:
      static: us-east-1
    stack:
      auto: false
logging:
  level.com.amazonaws.util.EC2MetadataUtils: error

message:
  topic:
    example-topic: example-topic
  queue:
    example-queue: example-queue
